import axios from "axios";
import React from "react";
import { ReactSearchAutocomplete } from "react-search-autocomplete";
import "../style/base.css";
import "../style/main.css";
import "../style/responsive.css";


function Search(props) {
  const fromEng = props.fromEng;
  // note: the id field is mandatory
  const items1 = [
    {
      idx: 0,
      en: "a-",
      vn: "kh\u00f4ng,v\u00f4, m\u1ea5t",
      word_type: "pref.",
      word_type_vn: "ti\u1ec1n t\u1ed1",
    },
    {
      idx: 1,
      en: "ab-",
      vn: " r\u1eddi, xa, gi\u1ea1ng,t\u00e1ch xa",
      word_type: "pref.",
      word_type_vn: "ti\u1ec1n t\u1ed1",
    },
    {
      idx: 2,
      en: "abacterial",
      vn: "kh\u00f4ng c\u00f3 vi khu\u1ea9n, phi khu\u1ea9n",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 3,
      en: "abaptiston",
      vn: "khoan s\u1ecd an to\u00e0n ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 4,
      en: "abaragnosis",
      vn: "m\u1ea5t nh\u1eadn th\u1ee9c tr\u1ecdng l\u01b0\u1ee3ng, m\u1ea5t tr\u1ecdng l\u01b0\u1ee3ng th\u1ee9c ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 5,
      en: "abarthrosis",
      vn: "kh\u1edbp \u0111\u1ed9ng ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 6,
      en: "abarticular",
      vn: "1. kh\u00f4ng g\u00e2y t\u1ed5n kh\u1edbp. 2.ngo\u00e0i kh\u1edbp ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 7,
      en: "abarticulation",
      vn: "1. sai kh\u1edbp. 2. kh\u1edbp \u0111\u1ed9ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 9,
      en: "abate",
      vn: "gi\u1ea3m, l\u00e0m gi\u00e0m",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 10,
      en: "abatement",
      vn: "gi\u1ea3m (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 11,
      en: "abaxial",
      vn: "xa tr\u1ee5c",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 12,
      en: "abbau",
      vn: "v\u1eadt ph\u1ea9m d\u1ecb h\u00f3a",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 13,
      en: "abdomen",
      vn: "b\u1ee5ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 14,
      en: "abdominal",
      vn: "b\u1ee5ng (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 15,
      en: "abdominocentesis",
      vn: "ch\u1ecdc b\u1ee5ng (thth) , ch\u1ecdc c\u1ed5 tr\u01b0\u1edbng (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 16,
      en: "abdominocystic",
      vn: "b\u1ee5ng-t\u00fai m\u1eadt (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 17,
      en: "abdominogenital",
      vn: "b\u1ee5ng-sinh d\u1ee5c (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 18,
      en: "abdominohysterectomy",
      vn: "c\u1eaft b\u1ecf t\u1eed cung qua b\u1ee5ng (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 19,
      en: "abdominohysterotomy",
      vn: "m\u1edf t\u1eed cung qua b\u1ee5ng (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 20,
      en: "abdominoscopy",
      vn: "soi xoang b\u1ee5ng (ph\u00e9p)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 21,
      en: "abdominoscrotal",
      vn: "b\u1ee5ng-b\u00ecu (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 22,
      en: "abdominothoracic",
      vn: "b\u1ee5ng-ng\u1ef1c (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 23,
      en: "abdominovaginal",
      vn: "b\u1ee5ng-\u00e2m \u0111\u1ea1o (th) ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 24,
      en: "abdominovesical",
      vn: "b\u1ee5ng-b\u00e0ng quang (th) ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 25,
      en: "abducens",
      vn: "gi\u1ea1ng, c\u01a1 gi\u1ea1ng",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 26,
      en: "abducent",
      vn: "gi\u1ea1ng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 27,
      en: "abduct",
      vn: "gi\u1ea1ng",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 28,
      en: "abduction",
      vn: "gi\u1ea1ng (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 29,
      en: "abductor",
      vn: "c\u01a1 gi\u1ea1ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 30,
      en: "abembryonic",
      vn: "ngo\u00e0i ph\u00f4i, xa ph\u00f4i",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 31,
      en: "abequose",
      vn: "abequose ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 32,
      en: "aberrancy",
      vn: "1. sai , sai l\u1ec7ch  2. sai h\u00ecnh ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 33,
      en: "aberrant",
      vn: "sai. l\u1ec7ch",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 34,
      en: "abetalipoproteinemia",
      vn: "thi\u1ebfu betalipoprotein-huy\u1ebft",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 35,
      en: "abiatrophy",
      vn: "m\u1ea5t sinh l\u1ef1c (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 36,
      en: "abient",
      vn: "tr\u00e1nh k\u00edch th\u00edch",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 37,
      en: "abiology",
      vn: "v\u00f4 sinh v\u1eadt h\u1ecdc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 38,
      en: "abirritant",
      vn: "gi\u1ea3m k\u00edch th\u00edch (t\u00e1c nh\u00e2n)",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 39,
      en: "abirritation",
      vn: "1. gi\u1ea3m \u0111\u00e1p \u1ee9ng k\u00edch th\u00edch. 2.m\u1ea5t tr\u01b0\u01a1ng l\u1ef1c ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 40,
      en: "abirritative",
      vn: "1. gi\u1ea3m c\u1ea3m \u1ee9ng,  2. \u00eam d\u1ecbu",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 41,
      en: "ablactation",
      vn: "1. cai s\u1eeda (s\u1ef1) . 2. c\u1ea1n s\u1eefa ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 42,
      en: "ablastemic",
      vn: "kh\u00f4ng thu\u1ed9c s\u1ef1 m\u1ecdc m\u1ea7m, phi nha t\u00ednh",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 43,
      en: "ablate",
      vn: "1.bong, t\u00e1ch . 2. c\u1eaft b\u1ecf ",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 44,
      en: "ablatio . ablation",
      vn: "1.bong, t\u00e1ch (s\u1ef1). 2. c\u1eaft b\u1ecf (s\u1ef1)                           ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 45,
      en: "ablepsia",
      vn: "m\u00f9 ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 46,
      en: "abluent",
      vn: "t\u1ea9y (thu\u1ed1c), thu\u1ed1c r\u1eeda v\u1ebft th\u01b0\u01a1ng",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 47,
      en: "abluminal",
      vn: "t\u1eeb l\u00f2ng \u1ed1ng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 48,
      en: "ablution",
      vn: "t\u1eafm, r\u1eeda (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 49,
      en: "ablutomania",
      vn: "t\u1eafm r\u1eeda (\u00e1m)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 50,
      en: "abmortal",
      vn: " t\u1eeb m\u00f4 ch\u1ebft (ch\u1ec9 t\u00e1c \u0111\u1ed9ng c\u1ee7a d\u00f2ng \u0111i\u1ec7n \u0111\u1ebfn m\u00f4 t\u1ed5n th\u01b0\u01a1ng)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 51,
      en: "abnormal",
      vn: "b\u1ea5t th\u01b0\u1eddng, d\u1ecb th\u01b0\u1eddng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 52,
      en: "abnormality",
      vn: "1. d\u1ecb th\u01b0\u1eddng, d\u1ecb d\u1ea1ng. 2. bi\u1ebfn ch\u1ea5t, bi\u1ebfn t\u00ednh",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 53,
      en: "abomasum",
      vn: "d\u1ea1 m\u00fai kh\u1ebf (lo\u00e0i nhai l\u1ea1i)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 54,
      en: "aborad",
      vn: "t\u1eeb mi\u1ec7ng ra",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 55,
      en: "aboral",
      vn: "\u0111\u1ed1i di\u1ec7n mi\u1ec7ng, xa mi\u1ec7ng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 56,
      en: "aboriginal",
      vn: "th\u1ed5 d\u00e2n (th), b\u1ea3n x\u1ee9 (th)",
      word_type: "a.n",
      word_type_vn: "a.n",
    },
    {
      idx: 57,
      en: "abort",
      vn: "1. ch\u1eb7n ti\u1ebfn tri\u1ec3n; s\u1ea9y thai. 2. l\u00e0m s\u1ea9y thai ",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 58,
      en: "abortion",
      vn: "s\u1ea9y thai, g\u00e2y s\u1ea9y thai (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 59,
      en: "abortionist",
      vn: "ph\u00e1 thai (ng\u01b0\u1eddi)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 60,
      en: "abortive",
      vn: "1. k\u00e9m ph\u00e1t tri\u1ec3n . 2. g\u00e2y s\u1ea9y thai, ch\u1ebft non. 3. ch\u1eb7n b\u1ec7nh",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 61,
      en: "abortus",
      vn: "thai ch\u1ebft",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 62,
      en: "abouchement",
      vn: "ti\u1ebfp kh\u1ea9u (s\u1ef1)",
      word_type: "F",
      word_type_vn: "F",
    },
    {
      idx: 63,
      en: "abrachiocephalia",
      vn: "thi\u1ebfu c\u00e1nh tay-\u0111\u1ea7u ( qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 64,
      en: "abrachiocephalus",
      vn: "thi\u1ebfu c\u00e1nh tay-\u0111\u1ea7u  (qu\u00e1i thai )",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 65,
      en: "abrachius",
      vn: "thi\u1ebfu c\u00e1nh tay (qu\u00e1i thai)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 66,
      en: "abrade",
      vn: "h\u1edbt da; m\u00e0i m\u00f2n ",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 67,
      en: "abrasion",
      vn: "h\u1edbt da; m\u00e0i m\u00f2n (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 68,
      en: "abrasive",
      vn: "1. g\u00e2y m\u00e0i m\u00f2n. 2. m\u00e0i m\u00f2n (ch\u1ea5t)",
      word_type: "a.n",
      word_type_vn: "a.n",
    },
    {
      idx: 69,
      en: "abrasor",
      vn: "m\u00e0i m\u00f2n (d\u1ee5ng c\u1ee5)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 70,
      en: "abreaction",
      vn: "tr\u00fat h\u1ebft phi\u1ec1n mu\u1ed9n, gi\u1ea3i t\u1ecfa c\u1ea3m x\u00fac",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 71,
      en: "abreuography",
      vn: "ch\u1ee5p tia X hu\u1ef3nh quang (ph\u00e9p)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 72,
      en: "abrin",
      vn: "abrin (\u0111\u1ed9c t\u1ed1 c\u00e2y t\u01b0\u01a1ng t\u01b0) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 73,
      en: "abrism",
      vn: "ng\u1ed9 \u0111\u1ed9c c\u00e2y t\u01b0\u01a1ng t\u01b0",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 74,
      en: "abrosia",
      vn: "ki\u00eang \u0103n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 75,
      en: "abruptio",
      vn: "ph\u00e2n ly (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 76,
      en: "abs-",
      vn: "xa, ly, t\u1eeb",
      word_type: "pref.",
      word_type_vn: "ti\u1ec1n t\u1ed1",
    },
    {
      idx: 77,
      en: "abscess",
      vn: "\u00e1p xe  ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 78,
      en: "abscessus",
      vn: "\u00e1p xe  ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 79,
      en: "abscise",
      vn: "c\u1eaft b\u1ecf",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 80,
      en: "abscissa",
      vn: "ho\u00e0nh \u0111\u1ed9",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 81,
      en: "abscission",
      vn: "c\u1eaft b\u1ecf (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 82,
      en: "absconsio",
      vn: "\u1ed5 kh\u1edbp",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 83,
      en: "abscopal",
      vn: "li\u00ean quan xa (ch\u1ec9 t\u00e1c \u0111\u1ed9ng \u0111\u1ebfn m\u00f4 \u1edf xa m\u00f4 b\u1ecb ph\u00f3ng x\u1ea1 )",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 84,
      en: "absence",
      vn: "1. \u0111\u1ed9ng kinh nh\u1ecf. 2.c\u01a1n v\u1eafng  (\u0111\u1ed9ng kinh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 85,
      en: "Absidia",
      vn: "Absidia (n\u1ea5m)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 86,
      en: "absinthe",
      vn: "kh\u1ed5 ng\u1ea3i (c\u00e2y)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 87,
      en: "absinthium",
      vn: "kh\u1ed5 ng\u1ea3i (c\u00e2y)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 88,
      en: "absolute",
      vn: "tuy\u1ec7t \u0111\u1ed1i",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 89,
      en: "absorb",
      vn: "h\u1ea5p thu  ",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 90,
      en: "absorbefacient",
      vn: "1. h\u1ea5p thu (g\u00e2y). 2. h\u1ea5p thu (ch\u1ea5t g\u00e2y) ",
      word_type: "a.n",
      word_type_vn: "a.n",
    },
    {
      idx: 91,
      en: "absorbent",
      vn: "h\u1ea5p thu ; h\u1ea5p thu (ch\u1ea5t) ",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 92,
      en: "absorptiometer",
      vn: "h\u1ea5p thu k\u1ebf",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 93,
      en: "absorptiometry",
      vn: "\u0111o \u0111\u1ed9 h\u1ea5p thu  (ph\u00e9p)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 94,
      en: "absorption",
      vn: "h\u1ea5p thu (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 95,
      en: "absorptive",
      vn: "1.h\u1ea5p thu \u0111\u01b0\u1ee3c 2.h\u1ea5p thu ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 96,
      en: "absorptivity",
      vn: "h\u1ec7 s\u1ed1 h\u1ea5p thu, h\u1ea5p thu (h\u1ec7 s\u1ed1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 97,
      en: "abstemious",
      vn: "ki\u00eang r\u01b0\u1ee3u ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 98,
      en: "abstergent",
      vn: "l\u00e0m s\u1ea1ch,t\u1ea3o th\u01b0\u01a1ng(s\u1ef1) ",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 99,
      en: "abstinence",
      vn: "ki\u00eang, nh\u1ecbn (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 100,
      en: "abstract",
      vn: "t\u00f3m t\u1eaft",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 101,
      en: "abstraction",
      vn: "1. chi\u1ebft, r\u00fat ra (s\u1ef1). 2. h\u00e0m d\u1ee9\u01a1i m\u1ee9c (RHM) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 102,
      en: "abterminal",
      vn: "chuy\u1ec3n t\u1eeb cu\u1ed1i t\u1edbi trung t\u00e2m (ch\u1ec9 d\u00f2ng \u0111i\u1ec7n \u1edf c\u01a1)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 103,
      en: "abtorsion",
      vn: "xoay m\u1eaft ra ngo\u00e0i",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 104,
      en: "abuse",
      vn: "l\u1ea1m d\u1ee5ng (s\u1ef1). 2. ng\u01b0\u1ee3c \u0111\u00e3i, t\u00e0n nh\u1eabn (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 105,
      en: "abut",
      vn: "ti\u1ebfp gi\u00e1p v\u1edbi",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 106,
      en: "abutment",
      vn: "tr\u1ee5 (RHM)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 107,
      en: "Acacia",
      vn: "keo Acacia (c\u00e2y)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 108,
      en: "acacia",
      vn: "g\u00f4m arabic",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 109,
      en: "acalcerosis",
      vn: "thi\u1ebfu  canxi ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 110,
      en: "acalcicosis",
      vn: "thi\u1ebfu  canxi (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 111,
      en: "acalculia",
      vn: "m\u1ea5t to\u00e1n n\u0103ng (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 112,
      en: "acampsia",
      vn: "c\u1ee9ng kh\u1edbp",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 114,
      en: "acantha",
      vn: "1.c\u1ed9t s\u1ed1ng. 2. m\u1ecfm gai ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 115,
      en: "acanthaceous",
      vn: "gai (c\u00f3)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 116,
      en: "acanthamebiasis",
      vn: "nhi\u1ec5m Acanthamoeba",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 117,
      en: "Acanthamoeba",
      vn: "Acanthamoeba (nguy\u00ean sinh \u0111\u1ed9ng v\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 118,
      en: "acanthesthesia",
      vn: "d\u1ecb c\u1ea3m gai \u0111\u00e2m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 119,
      en: "acanthion",
      vn: "\u0111i\u1ec3m nh\u1ecdn gai m\u0169i tr\u01b0\u1edbc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 120,
      en: "Acanthocephala",
      vn: "Giun \u0111\u1ea7u gai (l\u1edbp)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 121,
      en: "acanthocephalan",
      vn: "giun \u0111\u1ea7u gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 122,
      en: "acanthocephaliasis",
      vn: "giun \u0111\u1ea7u gai (bh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 123,
      en: "acanthocephalous",
      vn: "giun \u0111\u1ea7u gai (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 124,
      en: "acanthocheilonemiasis",
      vn: "nhi\u1ec5m giun ch\u1ec9 Mansonella",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 125,
      en: "acanthocyte",
      vn: "t\u1ebf b\u00e0o gai, h\u1ed3ng t\u1ebf b\u00e0o gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 126,
      en: "acanthocytosis",
      vn: "b\u1ec7nh t\u1ebf b\u00e0o gai, b\u1ec7nh h\u1ed3ng t\u1ebf b\u00e0o gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 127,
      en: "acanthoid",
      vn: "d\u1ea1ng gai",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 128,
      en: "acanthoma",
      vn: "u gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 130,
      en: "acarbia",
      vn: "gi\u1ea3m bicarbonat-huy\u1ebft",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 131,
      en: "acardia",
      vn: "kh\u00f4ng tim (qu\u00e1i t\u01b0\u1ee3ng )",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 132,
      en: "acardiac",
      vn: "kh\u00f4ng tim",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 133,
      en: "acarian",
      vn: "ve, b\u00e9t (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 134,
      en: "acariasis",
      vn: "nhi\u1ec5m ve, b\u00e9t (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 135,
      en: "acaricide",
      vn: "di\u1ec7t ve, b\u00e9t (thu\u1ed1c)",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 136,
      en: "acarid",
      vn: "b\u1ecd m\u00e1t",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 137,
      en: "Acaridae",
      vn: "Ve, b\u00e9t (h\u1ecd)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 138,
      en: "acaridan",
      vn: "ve, b\u00e9t",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 139,
      en: "Acarina",
      vn: "Ve, b\u00e9t  (b\u1ed9)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 140,
      en: "acarine",
      vn: "ve, b\u00e9t (lo\u1ea1i)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 141,
      en: "acarodermatitis",
      vn: "vi\u00eam da do ve",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 142,
      en: "acaroid",
      vn: "d\u1ea1ng ve, d\u1ea1ng b\u00e9t ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 143,
      en: "acarologist",
      vn: "ve b\u00e9t (chuy\u00ean gia), h\u1ecdc gia t\u1ef3 m\u00e3n ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 144,
      en: "acarology",
      vn: "t\u1ef3 m\u00e3n h\u1ecdc (m\u00f4n h\u1ecdc v\u1ec1 ve b\u00e9t)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 145,
      en: "acarophobia",
      vn: "s\u1ee3 ve ; s\u1ee3 v\u1eadt nh\u1ecdn (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 146,
      en: "acarotoxic",
      vn: "di\u1ec7t ve b\u00e9t",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 147,
      en: "acarus",
      vn: "t\u00edc, ve. b\u00e9t",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 148,
      en: "Acarus",
      vn: "t\u00edc, ve. b\u00e9t (lo\u00e0i)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 149,
      en: "acaryote",
      vn: "kh\u00f4ng nh\u00e2n (t\u1ebf b\u00e0o)",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 150,
      en: "acatalepsia",
      vn: "1. kh\u00f4ng hi\u1ec3u (s\u1ef1) 2. ch\u1ea9n \u0111o\u00e1n kh\u00f4ng ch\u1eafc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 151,
      en: "acatamathesia",
      vn: "1.lo\u1ea1n tri ng\u00f4n. 2. suy kh\u1ea3 n\u0103ng tri gi\u00e1c ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 152,
      en: "acataphasia",
      vn: "lo\u1ea1n di\u1ec5n ng\u00f4n (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 153,
      en: "acathexis",
      vn: "m\u1ea5t \u0111\u1ea7u t\u01b0  t\u00e2m n\u0103ng, m\u1ea5t t\u1eadp trung t\u01b0 t\u01b0\u1edfng [[th\u1ea5t qu\u00e1n ch\u00fa]]",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 154,
      en: "acathisia",
      vn: "ng\u1ed3i kh\u00f4ng y\u00ean (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 155,
      en: "acaulinosis",
      vn: "b\u1ec7nh n\u1ea5m acaulinum",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 156,
      en: "accelerant",
      vn: " x\u00fac t\u00e1c (ch\u1ea5t), ch\u1ea5t x\u00fac t\u00e1c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 157,
      en: "acceleration",
      vn: "gia t\u1ed1c (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 158,
      en: "accelerator",
      vn: "1. gia t\u1ed1c (ch\u1ea5t);  x\u00fac ti\u1ebfn (ch\u1ea5t). 2. th\u1ea7n kinh gia t\u1ed1c, c\u01a1 gia t\u1ed1c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 159,
      en: "accelerin",
      vn: "axelerin, y\u1ebfu t\u1ed1 V",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 160,
      en: "accelerometer",
      vn: "gia t\u1ed1c k\u1ebf",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 161,
      en: "accentuation",
      vn: "t\u0103ng c\u01b0\u1eddng (s\u1ef1), t\u0103ng n\u0103ng (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 162,
      en: "acceptor",
      vn: "ch\u1ea5t nh\u1eadn, th\u1ee5 th\u1ec3",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 163,
      en: "access",
      vn: "ti\u1ebfp c\u1eadn (s\u1ef1) ; c\u01a1n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 164,
      en: "accessiflexor",
      vn: "c\u01a1 g\u1ea5p ph\u1ee5",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 165,
      en: "accessorius",
      vn: "ph\u1ee5",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 166,
      en: "accessory",
      vn: "ph\u1ee5",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 167,
      en: "accident",
      vn: "tai n\u1ea1n; tai bi\u1ebfn, bi\u1ebfn c\u1ed1 ",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 168,
      en: "accident prone",
      vn: "thi\u00ean h\u01b0\u1edbng b\u1ecb tai n\u1ea1n ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 169,
      en: "accidentalism",
      vn: "duy tri\u1ec7u ch\u1ee9ng lu\u1eadn",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 170,
      en: "accommodation",
      vn: "\u0111i\u1ec1u ti\u1ebft (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 171,
      en: "accommodative",
      vn: "\u0111i\u1ec1u ti\u1ebft (th) ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 172,
      en: "accommodometer",
      vn: "\u0111i\u1ec1u ti\u1ebft  k\u1ebf",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 174,
      en: "accouchement",
      vn: "sinh \u0111\u1ebb (s\u1ef1) ; \u0111\u1ee1 \u0111\u1ebb (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 177,
      en: "accrementition",
      vn: "t\u0103ng tr\u01b0\u1edfng (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 178,
      en: "accretio",
      vn: "d\u00ednh b\u1ea5t th\u01b0\u1eddng (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 179,
      en: "accretion",
      vn: "1. t\u0103ng tr\u01b0\u1edfng (s\u1ef1)  2. d\u00ednh k\u1ebft (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 180,
      en: "accuracy",
      vn: "ch\u00ednh x\u00e1c (s\u1ef1, \u0111\u1ed9)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 182,
      en: "acedia",
      vn: "tr\u1ea7m c\u1ea3m ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 183,
      en: "acellular",
      vn: "v\u00f4 b\u00e0o",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 184,
      en: "acelomate",
      vn: "kh\u00f4ng khoang ,thi\u1ebfu \u1ed1ng ti\u00eau h\u00f3a",
      word_type: "a ",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 185,
      en: "acelous",
      vn: "kh\u00f4ng l\u00f5m m\u1eb7t (ch\u1ec9 m\u1ed9t s\u1ed1 \u0111\u1ed9ng v\u1eadt c\u00f3 x\u01b0\u01a1ng s\u1ed1ng)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 186,
      en: "acenesthesia",
      vn: "m\u1ea5t  kho\u00e1i c\u1ea3m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 187,
      en: "acentric",
      vn: "1. ngo\u00e0i trung t\u00e2m. 2. thi\u1ebfu t\u00e2m \u0111\u1ed9ng ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 188,
      en: "acephalobrachia",
      vn: "kh\u00f4ng \u0111\u1ea7u-tay (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 189,
      en: "acephalobrachius",
      vn: "kh\u00f4ng \u0111\u1ea7u-tay (qu\u00e1i thai)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 190,
      en: "acephalocardia",
      vn: "kh\u00f4ng \u0111\u1ea7u-tim (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 191,
      en: "acephalocardius",
      vn: "kh\u00f4ng \u0111\u1ea7u-tim (qu\u00e1i thai)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 192,
      en: "acephalochiria",
      vn: "kh\u00f4ng \u0111\u1ea7u-b\u00e0n tay (qu\u00e1i t\u01b0\u1ee3ng) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 193,
      en: "acephalochirus",
      vn: "kh\u00f4ng \u0111\u1ea7u-b\u00e0n tay (qu\u00e1i thai)  ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 194,
      en: "acephalocyst",
      vn: "nang s\u00e1n kh\u00f4ng \u0111\u1ea7u, k\u00e9n s\u00e1n kh\u00f4ng \u0111\u1ea7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 195,
      en: "acephalogaster",
      vn: "kh\u00f4ng \u0111\u1ea7u-b\u1ee5ng (qu\u00e1i thai) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 196,
      en: "acephalogastria",
      vn: "kh\u00f4ng \u0111\u1ea7u-b\u1ee5ng  (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 197,
      en: "acephalopodia",
      vn: " kh\u00f4ng \u0111\u1ea7u-ch\u00e2n (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 198,
      en: "acephalopodius",
      vn: "kh\u00f4ng \u0111\u1ea7u-ch\u00e2n (qu\u00e1i thai) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 199,
      en: "acephalorhachia",
      vn: " kh\u00f4ng \u0111\u1ea7u-c\u1ed9t s\u1ed1ng (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 200,
      en: "acephalostomia",
      vn: "kh\u00f4ng \u0111\u1ea7u-m\u1ed3m (m\u1ed3m th\u00f4 s\u01a1) (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 201,
      en: "acephalostomus",
      vn: "kh\u00f4ng \u0111\u1ea7u-m\u1ed3m (m\u1ed3m th\u00f4 s\u01a1) (qu\u00e1i thai)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 202,
      en: "acephalothoracia",
      vn: "kh\u00f4ng \u0111\u1ea7u-ng\u1ef1c (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 203,
      en: "acephalothorus",
      vn: "kh\u00f4ng \u0111\u1ea7u-ng\u1ef1c (qu\u00e1i thai) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 204,
      en: "acephalous",
      vn: "kh\u00f4ng \u0111\u1ea7u ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 205,
      en: "acephalus",
      vn: " kh\u00f4ng \u0111\u1ea7u (qu\u00e1i thai)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 206,
      en: "acephaly",
      vn: " kh\u00f4ng \u0111\u1ea7u (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 207,
      en: "acervuline",
      vn: "chen ch\u00fac, d\u00e0y \u0111\u1eb7t (ch\u1ec9 h\u1ea1ch)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 208,
      en: "acervulus",
      vn: "c\u00e1t n\u00e3o",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 209,
      en: "acescence",
      vn: "1. v\u1ecb chua. 2. bi\u1ebfn th\u00e0nh chua (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 210,
      en: "acescent",
      vn: "h\u01a1i chua, acid nh\u1eb9",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 211,
      en: "acetabular",
      vn: "\u1ed5 c\u1ed1i (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 212,
      en: "acetabulectomy",
      vn: "c\u1eaft b\u1ecf \u1ed5 c\u1ed1i (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 213,
      en: "acetabuloplasty",
      vn: "t\u1ea1o h\u00ecnh \u1ed5 c\u1ed1i (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 214,
      en: "acetabulum",
      vn: "\u1ed5 c\u1ed1i",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 215,
      en: "acetal",
      vn: "acetal ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 216,
      en: "acetaldehyde",
      vn: "acetaldehyd, etanal",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 217,
      en: "acetaminophen",
      vn: "paracetamol",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 218,
      en: "acetate",
      vn: "acetat",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 219,
      en: "aceteugenol",
      vn: "d\u1ea7u \u0111inh h\u01b0\u01a1ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 220,
      en: "acetic",
      vn: "acetic",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 221,
      en: "aceticoceptor",
      vn: "ch\u1ea5t nh\u1eadn acetyl",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 222,
      en: "acetify",
      vn: "acid acetic h\u00f3a",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 223,
      en: "acetimeter",
      vn: "acid acetic k\u1ebf, acid k\u1ebf \u0111o gi\u1ea5m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 224,
      en: "acetin",
      vn: "acetin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 225,
      en: "acetoacetate",
      vn: "acetoacetat",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 226,
      en: "Acetobacter",
      vn: "Acetobacter, men gi\u1ea5m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 227,
      en: "acetolysis",
      vn: "Ph\u00e2n h\u1ee7y b\u1eb1ng acid ho\u1eb7c anhydrid acetic ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 228,
      en: "acetonation",
      vn: "h\u00f3a h\u1ee3p aceton (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 229,
      en: "acetone",
      vn: "aceton",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 230,
      en: "acetonemia",
      vn: "axeton-huy\u1ebft ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 231,
      en: "acetonglycosuria",
      vn: "aceton-glucose-ni\u1ec7u, aceton-\u0111\u01b0\u1eddng-ni\u1ec7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 232,
      en: "acetonitrile",
      vn: "acetonitril",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 233,
      en: "acetonum",
      vn: "aceton",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 234,
      en: "acetonumerator",
      vn: "\u0111\u1ecbnh l\u01b0\u1ee3ng aceton n\u01b0\u1edbc ti\u1ec3u (d\u1ee5ng c\u1ee5)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 235,
      en: "acetonuria",
      vn: "aceton-ni\u1ec7u ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 236,
      en: "acetosoluble",
      vn: "tan trong acid acetic ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 237,
      en: "acetous",
      vn: "gi\u1ea5m (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 238,
      en: "acetum",
      vn: "1. gi\u1ea5m. 2. thu\u1ed1c ng\u00e2m gi\u1ea5m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 239,
      en: "acetyl",
      vn: "acetyl",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 240,
      en: "acetylase",
      vn: "acetylase",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 241,
      en: "acetylation",
      vn: "acetyl-ho\u00e1 (s\u1ef1) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 242,
      en: "acetylator",
      vn: "sinh v\u1eadt axetyl-h\u00f3a (c\u00f3 kh\u1ea3 n\u0103ng acetyl h\u00f3a trong chuy\u1ec3n h\u00f3a)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 243,
      en: "acetylcholine",
      vn: "acetylcholin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 244,
      en: "acetylcholinesterase",
      vn: "acetylcholinesterase",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 245,
      en: "acetylcysteine",
      vn: "acetylcystein",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 246,
      en: "acetylene",
      vn: "acetylen",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 247,
      en: "acetyltransferase",
      vn: "acetyltransferase ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 248,
      en: "achalasia",
      vn: "kh\u00f4ng gi\u00e3n \u0111\u01b0\u1ee3c, m\u1ea5t gi\u00e3n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 249,
      en: "ache",
      vn: "\u0111au bu\u1ed1t",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 250,
      en: "acheiria",
      vn: "thi\u1ebfu b\u00e0n tay (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 251,
      en: "acheiropodia",
      vn: "thi\u1ebfu b\u00e0n tay-b\u00e0n ch\u00e2n (t\u1eadt) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 252,
      en: "acheirus",
      vn: "thi\u1ebfu b\u00e0n tay (qu\u00e1i thai) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 254,
      en: "achillobursitis",
      vn: "vi\u00eam bao g\u00e2n g\u00f3t",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 255,
      en: "achillodynia",
      vn: "\u0111au (vi\u00eam) bao g\u00e2n g\u00f3t",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 256,
      en: "achillorraphy",
      vn: "kh\u00e2u g\u00e2n g\u00f3t (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 257,
      en: "acholia",
      vn: "thi\u1ebfu m\u1eadt, gi\u1ea3m ti\u1ebft m\u1eadt",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 258,
      en: "acholic",
      vn: "kh\u00f4ng c\u00f3 m\u1eadt",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 260,
      en: "achondrogenesis",
      vn: "gi\u1ea3m s\u1ea3n s\u1ee5n (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 261,
      en: "achoresis",
      vn: "gi\u1ea3m th\u1ec3 t\u00edch  (c\u1ee7a c\u01a1 quan)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 262,
      en: "Achorion",
      vn: "Trichophiton (n\u1ea5m)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 263,
      en: "achreocytemia",
      vn: "gi\u1ea3m s\u1eafc h\u1ed3ng t\u1ebf b\u00e0o",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 264,
      en: "achromasia",
      vn: "1. m\u1ea5t s\u1eafc da. 2. kh\u00f4ng b\u1eaft m\u00e0u ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 265,
      en: "achromat",
      vn: "1. th\u1ea5u k\u00ednh ti\u00eau s\u1eafc . 2. ng\u01b0\u1eddi m\u00f9 s\u1eafc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 266,
      en: "achromate",
      vn: "m\u00f9 s\u1eafc (ng\u01b0\u1eddi), m\u00f9 m\u00e0u (ng\u01b0\u1eddi)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 267,
      en: "achromatic",
      vn: "1.kh\u00f4ng l\u00e0m b\u1ea1c m\u00e0u.2. kh\u00f3 b\u1eaft m\u00e0u  3. ti\u00eau s\u1eafc,acromatic ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 268,
      en: "achromatism",
      vn: "1. ti\u00eau s\u1eafc (t\u00ednh), kh\u00f3 nhu\u1ed9m m\u00e0u. 2. m\u00f9 m\u00e0u (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 269,
      en: "achromatize",
      vn: "l\u00e0m ti\u00eau s\u1eafc , l\u00e0m m\u1ea5t m\u00e0u",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 270,
      en: "achromatocyte",
      vn: "h\u1ed3ng t\u1ebf b\u00e0o phai m\u00e0u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 271,
      en: "achromatolysis",
      vn: "dung gi\u1ea3i ch\u1ea5t kh\u00f4ng m\u00e0u (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 272,
      en: "achromatophil",
      vn: "kh\u00f4ng b\u1eaft m\u00e0u",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 273,
      en: "achromatophilia",
      vn: "kh\u00f4ng b\u1eaft m\u00e0u (t\u00ednh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 274,
      en: "achromatopia,achromatopsia",
      vn: "m\u00f9 m\u00e0u, m\u00f9 s\u1eafc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 275,
      en: "achromatopic",
      vn: "m\u00f9 m\u00e0u (ng\u01b0\u1eddi), m\u00f9 s\u1eafc (ng\u01b0\u1eddi)",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 276,
      en: "achromatosis",
      vn: "1.thi\u1ebfu s\u1eafc t\u1ed1   2.kh\u00f4ng b\u1eaft m\u00e0u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 277,
      en: "achromatous",
      vn: "v\u00f4 s\u1eafc, kh\u00f4ng m\u00e0u ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 278,
      en: "achromaturia",
      vn: "v\u00f4 s\u1eafc ni\u1ec7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 279,
      en: "achromocyte",
      vn: "th\u1ec3  h\u00ecnh li\u1ec1m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 280,
      en: "achromophilous",
      vn: "kh\u00f4ng b\u1eaft m\u00e0u",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 281,
      en: "achromotrichia",
      vn: "l\u00f4ng t\u00f3c kh\u00f4ng m\u00e0u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 282,
      en: "achrooamyloid",
      vn: "amyloid v\u00f4 s\u1eafc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 283,
      en: "achylia",
      vn: "thi\u1ebfu nh\u0169 tr\u1ea5p (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 284,
      en: "achylous",
      vn: "thi\u1ebfu nh\u0169 tr\u1ea5p",
      word_type: "a)                              ",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 285,
      en: "acicular",
      vn: "h\u00ecnh kim",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 286,
      en: " -aciculum",
      vn: "l\u00f4ng c\u1ee9ng g\u1ed1c (ti\u00ean mao tr\u00f9ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 287,
      en: "acid",
      vn: "acid",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 288,
      en: "acidalbumin",
      vn: "acidalbumin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 289,
      en: "acidaminuria",
      vn: "acid amin-ni\u1ec7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 290,
      en: "acidemia",
      vn: "acid-huy\u1ebft (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 291,
      en: "acid-fast",
      vn: "kh\u00e1ng acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 292,
      en: "acidic",
      vn: "acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 293,
      en: "acidifiable",
      vn: "c\u00f3 th\u1ec3 acid h\u00f3a",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 294,
      en: "acidifier",
      vn: "t\u0103ng acid h\u00f3a (ch\u1ea5t)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 295,
      en: "acidify",
      vn: "acid h\u00f3a",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 296,
      en: "acidimeter",
      vn: "acid k\u1ebf",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 297,
      en: "acidimetry",
      vn: "\u0111o acid (ph\u00e9p)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 298,
      en: "acidity",
      vn: "\u0111\u1ed9 acid, t\u00ednh acid, \u0111\u1ed9 chua",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 299,
      en: "acido-",
      vn: "acid ",
      word_type: "pref",
      word_type_vn: "ti\u1ec1n t\u1ed1",
    },
    {
      idx: 300,
      en: "acidocyte",
      vn: "t\u1ebf b\u00e0o \u01b0a acid. 2. t\u1ebf b\u00e0o \u01b0a eosin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 301,
      en: "acidogenesis",
      vn: "tr\u1edf th\u00e0nh acid",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 302,
      en: "acidogenic",
      vn: "sinh acid, sinh acid t\u00ednh",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 303,
      en: "acidology",
      vn: "thi\u1ebft b\u1ecb ngo\u1ea1i khoa h\u1ecdc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 304,
      en: "acidophilism",
      vn: "u tuy\u1ebfn y\u00ean \u01b0a acid (bh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 305,
      en: "acidoresistant",
      vn: "kh\u00e1ng acid; ch\u1ecbu acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 306,
      en: "acidosteophyte",
      vn: "gai x\u01b0\u01a1ng nh\u1ecdn \u0111\u1ea7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 307,
      en: "acidulated",
      vn: "1. acid nh\u1eb9.  2. acid h\u00f3a",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 308,
      en: "acidulous",
      vn: "acid nh\u1eb9, v\u1ecb acid ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 309,
      en: "aciduria",
      vn: "acid-ni\u1ec7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 310,
      en: "aciduric",
      vn: "dung n\u1ea1p acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 311,
      en: "acidyl",
      vn: "acyl (g\u1ed1c)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 312,
      en: "acidylation",
      vn: "acyl h\u00f3a (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 313,
      en: "acinar",
      vn: "tuy\u1ebfn nang (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 314,
      en: "acinic",
      vn: "tuy\u1ebfn nang (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 315,
      en: "aciniform",
      vn: "d\u1ea1ng tuy\u1ebfn nang",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 316,
      en: "acinitis",
      vn: "vi\u00eam tuy\u1ebfn nang",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 317,
      en: "acinose",
      vn: "1. g\u1ed3m tuy\u1ebfn nang .  2. tuy\u1ebfn nang (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 318,
      en: "acinotubular",
      vn: "tuy\u1ebfn nang d\u1ea1ng \u1ed1ng (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 319,
      en: "acinous",
      vn: "tuy\u1ebfn nang (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 320,
      en: "acinus",
      vn: "tuy\u1ebfn nang, ch\u00f9m nang ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 321,
      en: "acladiosis",
      vn: "vi\u00eam da do n\u1ea5m Acladium castellani ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 322,
      en: "Acladium",
      vn: "Acladium (n\u1ea5m) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 323,
      en: "aclastic",
      vn: "1. lo\u1ea1n s\u1ea3n c\u1ee5c b\u1ed9 (th). 2. kh\u00f4ng kh\u00fac x\u1ea1 ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 324,
      en: "acleistocardia",
      vn: "h\u1edf l\u1ed7 b\u1ea7u d\u1ee5c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 325,
      en: "aclusion",
      vn: "kh\u00f4ng kh\u1edbp c\u1eafn ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 326,
      en: "acme",
      vn: "c\u1ef1c \u0111i\u1ec3m,  th\u1eddi k\u1ef3 to\u00e0n ph\u00e1t",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 327,
      en: "acne",
      vn: "vi\u00eam nang b\u00e3;  vi\u00eam nang l\u00f4ng;  tr\u1ee9ng c\u00e1 ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 328,
      en: "acnegen",
      vn: "g\u00e2y tr\u1ee9ng c\u00e1 (ch\u1ea5t) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 329,
      en: "acnegenic",
      vn: "g\u00e2y tr\u1ee9ng c\u00e1",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 330,
      en: "acneiform",
      vn: "d\u1ea1ng tr\u1ee9ng c\u00e1",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 331,
      en: "acnemia",
      vn: "teo b\u1eafp ch\u00e2n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 332,
      en: "acnitis",
      vn: "vi\u00eam nang r\u00e3i r\u00e1c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 333,
      en: "acocantherin",
      vn: "ouabain",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 334,
      en: "acoelomate",
      vn: "kh\u00f4ng khoang (\u0111\u1ed9ng v\u1eadt)",
      word_type: "a.n",
      word_type_vn: "a.n",
    },
    {
      idx: 335,
      en: "aconative",
      vn: "thi\u1ebfu \u00fd ch\u00ed",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 336,
      en: "aconite",
      vn: "ph\u1ee5 t\u1eed, c\u1ee7 \u1ea5u t\u00e0u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 337,
      en: "aconitine",
      vn: "aconitin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 338,
      en: "Aconitum",
      vn: "ph\u1ee5 t\u1eed (c\u00e2y)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 339,
      en: "aconuresis",
      vn: "\u0111\u00e1i d\u1ea7m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 340,
      en: "acorea",
      vn: "kh\u00f4ng \u0111\u1ed3ng t\u1eed (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 341,
      en: "acoria",
      vn: "\u0103n kh\u00f4ng bi\u1ebft no (ch), tham th\u1ef1c (ch) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 342,
      en: "acormia",
      vn: "kh\u00f4ng th\u00e2n (qu\u00e1i t\u01b0\u1ee3ng )",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 343,
      en: "acortan",
      vn: "corticotropin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 344,
      en: "acou-",
      vn: "th\u00ednh, th\u00ednh gi\u00e1c",
      word_type: "pref",
      word_type_vn: "ti\u1ec1n t\u1ed1",
    },
    {
      idx: 345,
      en: "acouesthesia",
      vn: "th\u00ednh gi\u00e1c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 346,
      en: "acoumeter",
      vn: "th\u00ednh l\u1ef1c k\u1ebf, tr\u1eafc th\u00ednh k\u1ebf",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 347,
      en: "acousma",
      vn: "\u1ea3o th\u00ednh",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 348,
      en: "acousmatagnosis",
      vn: "\u0111i\u1ebfc t\u00e2m th\u1ea7n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 349,
      en: "acousmatamnesia",
      vn: "qu\u00ean \u00e2m (ch), qu\u00ean gi\u1ecdng (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 350,
      en: "acoustic",
      vn: "th\u00ednh gi\u00e1c (th), \u00e2m h\u1ecdc (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 351,
      en: "acousticophobia",
      vn: "s\u1ee3 \u00e2m thanh (\u00e1m)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 352,
      en: "acoustics",
      vn: "\u00e2m h\u1ecdc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 353,
      en: "acoustogram",
      vn: "\u00e2m \u0111\u1ed3",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 354,
      en: "acquired",
      vn: "m\u1eafc ph\u1ea3i",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 355,
      en: "acquisition",
      vn: "th\u00e0nh t\u1ef1u; c\u00e1i \u0111\u1ea1t \u0111\u01b0\u1ee3c ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 357,
      en: "acral",
      vn: "\u0111\u1ec9nh (th), ng\u1ecdn (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 358,
      en: "acrania",
      vn: "kh\u00f4ng s\u1ecd (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 359,
      en: "acranial",
      vn: "kh\u00f4ng s\u1ecd ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 360,
      en: "acranius",
      vn: "kh\u00f4ng s\u1ecd (qu\u00e1i thai) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 361,
      en: "acratia",
      vn: "m\u1ea5t s\u1ee9c  (s\u1ef1)",
      word_type: "n)                              ",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 362,
      en: "acraturesis",
      vn: "ti\u1ec3u ti\u1ec7n kh\u00f3 (do gi\u1ea3m tr\u01b0\u01a1ng l\u1ef1c b\u00e0ng quang)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 363,
      en: "acremoniosis",
      vn: "b\u1ec7nh n\u1ea5m Acremonium",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 364,
      en: "acribometer",
      vn: "vi tr\u1eafc k\u1ebf  ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 365,
      en: "acrid",
      vn: "cay",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 366,
      en: "acriflavine",
      vn: "acriflavin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 367,
      en: "acritical",
      vn: "kh\u00f4ng c\u00f3 c\u01a1n",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 368,
      en: "acritochromacy",
      vn: "m\u00f9 m\u00e0u (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 369,
      en: "acroagnosis",
      vn: "m\u1ea5t nh\u1eadn th\u1ee9c chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 370,
      en: "acroanesthesia",
      vn: "m\u1ea5t c\u1ea3m \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 371,
      en: "acroarthritis",
      vn: "vi\u00eam kh\u1edbp \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 372,
      en: "acroblast",
      vn: "nguy\u00ean c\u1ef1c \u0111\u1ea7u  (tinh tr\u00f9ng), m\u1ea7m th\u1ec3 ng\u1ecdn",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 373,
      en: "acrobrachycephaly",
      vn: "h\u1eb9p s\u1ecd (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 374,
      en: "acrobystiolith",
      vn: "s\u1ecfi bao quy \u0111\u1ea7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 375,
      en: "acrobystitis",
      vn: "vi\u00eam bao quy \u0111\u1ea7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 376,
      en: "acrocentric",
      vn: "t\u00e2m \u1edf \u0111\u1ea7u (c\u00f3), t\u00e2m \u1edf ng\u1ecdn (c\u00f3)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 377,
      en: "acrocephalic",
      vn: "\u0111\u1ea7u h\u00ecnh th\u00e1p (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 378,
      en: "acrocephalopolysyndactyly",
      vn: "\u0111\u1ea7u h\u00ecnh th\u00e1p d\u00ednh ng\u00f3n v\u00e0 th\u1eeba ng\u00f3n (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 379,
      en: "acrocephalosyndactyly",
      vn: "\u0111\u1ea7u h\u00ecnh th\u00e1p  d\u00ednh ng\u00f3n (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 380,
      en: "acrochordon",
      vn: "m\u1ee5n c\u01a1m c\u00f3 cu\u1ed1ng, u nh\u00fa c\u00f3 cu\u1ed1ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 381,
      en: "acrocontracture",
      vn: "co c\u1ee9ng c\u01a1 \u0111\u1ea7u chi (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 382,
      en: "acrocyanosis",
      vn: "xanh t\u00edm \u0111\u1ea7u chi (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 383,
      en: "acrodermatitis",
      vn: "vi\u00eam da \u0111\u1ea7u chi ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 384,
      en: "acrodermatosis",
      vn: "vi\u00eam da \u0111\u1ea7u chi (bh) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 385,
      en: "acrodolichomelia",
      vn: "\u0111\u1ea7u chi d\u00e0i (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 386,
      en: "acrodynia",
      vn: "\u0111au \u0111\u1ea7u chi (bh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 387,
      en: "acroesthesia",
      vn: "\u0111\u1ea7u chi ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 388,
      en: "acrognosis",
      vn: "nh\u1eadn th\u1ee9c chi (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 389,
      en: "acrohypothermy",
      vn: "l\u1ea1nh b\u00e0n tay b\u00e0n ch\u00e2n (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 390,
      en: "acrokeratosis",
      vn: "d\u00e0y s\u1eebng \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 391,
      en: "acrolein",
      vn: "acrolein",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 392,
      en: "acromacria",
      vn: "tay v\u01b0\u1ee3n (ch), ng\u00f3n tay (ch\u00e2n) v\u01b0\u1ee3n (ch), ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 393,
      en: "acromastitis",
      vn: "vi\u00eam n\u00fam v\u00fa",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 394,
      en: "acromegalic",
      vn: "to c\u1ef1c (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 395,
      en: "acromegalogigantism",
      vn: "to c\u1ef1c kh\u1ed5ng l\u1ed3 (bh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 396,
      en: "acromegaloidism",
      vn: "d\u1ea1ng to c\u1ef1c (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 397,
      en: "acromegaly",
      vn: "to c\u1ef1c (bh) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 398,
      en: "acromelalgia",
      vn: "\u0111au \u0111\u1ea7u chi (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 399,
      en: "acromelic",
      vn: "\u0111\u1ea7u chi (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 400,
      en: "acrometagenesis",
      vn: "d\u1ecb ph\u00e1t \u0111\u1ea7u chi, qu\u00e1 ph\u00e1t tri\u1ec3n \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 402,
      en: "acromial",
      vn: "m\u1ecfm c\u00f9ng vai (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 403,
      en: "acromioclavicular",
      vn: "m\u1ecfm c\u00f9ng vai-\u0111\u00f2n (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 404,
      en: "acromiocoracoid",
      vn: "m\u1ecfm c\u00f9ng vai-m\u1ecfm qu\u1ea1 (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 405,
      en: "acromiohumeral",
      vn: "m\u1ecfm c\u00f9ng vai-x\u01b0\u01a1ng c\u00e1nh tay (th) ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 406,
      en: "acromion",
      vn: "m\u1ecfm c\u00f9ng vai ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 407,
      en: "acromionectomy",
      vn: "c\u1eaft m\u1ecfm c\u00f9ng vai (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 408,
      en: "acromioplasty",
      vn: "t\u1ea1o h\u00ecnh m\u1ecfm c\u00f9ng vai  (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 409,
      en: "acromioscapular",
      vn: "m\u1ecfm c\u00f9ng vai-x\u01b0\u01a1ng vai (th) ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 410,
      en: "acromiothoracic",
      vn: "m\u1ecfm c\u00f9ng vai-ng\u1ef1c (th) ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 411,
      en: "acromphalus",
      vn: "1. l\u1ed3i r\u1ed1n (ch). 2. trung t\u00e2m r\u1ed1n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 412,
      en: "acronarcotic",
      vn: "cay v\u00e0 g\u00e2y ng\u1ee7",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 413,
      en: "acroneurosis",
      vn: "lo\u1ea1n th\u1ea7n kinh \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 414,
      en: "acronym",
      vn: "\u0111\u1ea7u t\u1ef1 ng\u1eef (t\u1eeb c\u1ea5u t\u1ea1o b\u1eb1ng nh\u1eefng ch\u1eef \u0111\u1ea7u nh\u01b0 AIDS, LASER\u2026)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 415,
      en: "acro-osteolysis",
      vn: "ti\u00eau x\u01b0\u01a1ng \u0111\u1ea7u chi (ch), dung gi\u1ea3i x\u01b0\u01a1ng \u0111\u1ea7u chi (ch) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 416,
      en: "acropachy",
      vn: "ng\u00f3n d\u00f9i tr\u1ed1ng (ch) (tay ho\u1eb7c ch\u00e2n) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 417,
      en: "acropachyderma",
      vn: "d\u00e0y da c\u1ef1c \u0111\u1ea7u (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 418,
      en: "acroparalysis",
      vn: "li\u1ec7t \u0111\u1ea7u chi (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 419,
      en: "acroparesthesia",
      vn: "d\u1ecb c\u1ea3m \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 420,
      en: "acropathology",
      vn: "b\u1ec7nh h\u1ecdc \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 421,
      en: "acropathy",
      vn: "b\u1ec7nh \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 422,
      en: "acropetal",
      vn: "h\u01b0\u1edbng ng\u1ecdn",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 423,
      en: "acrophobia",
      vn: "s\u1ee3 n\u01a1i cao (\u00e1m)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 424,
      en: "acroposthitis",
      vn: "vi\u00eam bao quy \u0111\u1ea7u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 425,
      en: "acropurpura",
      vn: "ban xu\u1ea5t huy\u1ebft ng\u00f3n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 426,
      en: "acrosome",
      vn: "1. c\u1ef1c \u0111\u1ea7u (tinh tr\u00f9ng). 2. th\u1ec3 ng\u1ecdn (Th\u1ef1c)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 427,
      en: "acrospiroma",
      vn: "u ph\u1ea7n xa tuy\u1ebfn m\u1ed3 h\u00f4i",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 428,
      en: "acrostealgia",
      vn: "vi\u00eam \u0111au \u0111\u1ea7u m\u00f5m x\u01b0\u01a1ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 429,
      en: "acrosyndactyly",
      vn: "d\u00ednh ng\u00f3n \u0111\u1ea7u m\u00fat (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 430,
      en: "acroteric",
      vn: "\u0111\u1ea7u m\u00fat,  ngo\u00e0i c\u00f9ng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 431,
      en: "acrotic",
      vn: "1. b\u1ec1 m\u1eb7t (th). 2. v\u00f4 m\u1ea1ch",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 432,
      en: "acrotism",
      vn: "v\u00f4 m\u1ea1ch, m\u1ea1ch kh\u00f3 b\u1eaft",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 433,
      en: "acrotrophodynia",
      vn: "\u0111au \u0111\u1ea7u chi lo\u1ea1n d\u01b0\u1ee1ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 434,
      en: "acrotrophoneurosis",
      vn: "lo\u1ea1n d\u01b0\u1ee1ng th\u1ea7n kinh \u0111\u1ea7u chi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 435,
      en: "acrylic",
      vn: "acrylic",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 436,
      en: "act",
      vn: "h\u00e0nh vi ; \u0111\u1ed9ng t\u00e1c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 437,
      en: "actin",
      vn: "actin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 439,
      en: "acting out",
      vn: "manh \u0111\u1ed9ng (s\u1ef1), \u0111\u1ed9t kh\u1edfi(s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 440,
      en: "actinic",
      vn: " quang h\u00f3a",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 441,
      en: "actinicity",
      vn: "quang h\u00f3a (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 442,
      en: "actiniform",
      vn: "d\u1ea1ng t\u1ecfa tia",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 443,
      en: "actinium",
      vn: "actinium ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 444,
      en: "actinobacillosis",
      vn: "b\u1ec7nh do Actinobacillus",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 445,
      en: "Actinobacillus",
      vn: "Actinobacillus (tr\u1ef1c khu\u1ea9n)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 446,
      en: "actinochemistry",
      vn: "h\u00f3a quang h\u1ecdc ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 447,
      en: "actinocongestin",
      vn: "congestin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 448,
      en: "actinodermatitis",
      vn: "vi\u00eam da ph\u00f3ng x\u1ea1",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 449,
      en: "actinogenesis",
      vn: "ph\u00e1t b\u1ee9c x\u1ea1 (s\u1ef1),  ph\u00e1t ph\u00f3ng x\u1ea1 (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 450,
      en: "actinolite",
      vn: "actinolite  (ch\u1ea5t thay \u0111\u1ed5i do \u00e1nh s\u00e1ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 451,
      en: "actinology",
      vn: "x\u1ea1 quang h\u1ecdc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 452,
      en: "actinolyte",
      vn: "ph\u00e1t tia t\u1eed ngo\u1ea1i (m\u00e1y), ph\u00e1t tia c\u1ef1c t\u00edm (m\u00e1y)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 453,
      en: "actinometer",
      vn: "x\u1ea1 quang k\u1ebf, nh\u1eadt x\u1ea1 k\u1ebf",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 454,
      en: "actinometry",
      vn: "\u0111o c\u01b0\u1eddng \u0111\u1ed9 x\u1ea1 quang (ph\u00e9p)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 455,
      en: "actinomycelial",
      vn: "1. th\u1ec3 s\u1ee3i n\u1ea5m c\u1ee7a n\u1ea5m tia (th). 2. n\u1ea5m tia (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 456,
      en: "Actinomyces",
      vn: "N\u1ea5m tia, X\u1ea1 khu\u1ea9n (lo\u1ea1i)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 457,
      en: "Actinomycetaceae",
      vn: "N\u1ea5m tia, X\u1ea1 khu\u1ea9n (h\u1ecd)",
      word_type: "n)?",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 458,
      en: "Actinomycetales",
      vn: "N\u1ea5m tia, X\u1ea1 khu\u1ea9n (b\u1ed9)",
      word_type: "n)?",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 459,
      en: "actinomycetic",
      vn: "n\u1ea5m tia, x\u1ea1 khu\u1ea9n (th)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 460,
      en: "actinomycetin",
      vn: "actinomycetin ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 461,
      en: "actinomycetoma",
      vn: "u n\u1ea5m tia",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 462,
      en: "c",
      vn: "actinomycin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 463,
      en: "actinomycoma",
      vn: "u d\u1ea1ng do n\u1ea5m tia",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 464,
      en: "actinomycotin",
      vn: "actinomycotin ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 465,
      en: "actinophage",
      vn: "th\u1ef1c khu\u1ea9n th\u1ec3 n\u1ea5m tia",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 466,
      en: "actinophytosis",
      vn: "nhi\u1ec5m n\u1ea5m tia (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 467,
      en: "actinotherapy",
      vn: "quang li\u1ec7u ph\u00e1p",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 468,
      en: "actinotoxemia",
      vn: "nhi\u1ec5m \u0111\u1ed9c ph\u00f3ng x\u1ea1",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 469,
      en: "actinotoxin",
      vn: "\u0111\u1ed9c t\u1ed1 c\u1ecf ch\u00e2n ng\u1ed7ng bi\u1ec5n (hay h\u1ea3i qu\u1ef3)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 470,
      en: "action",
      vn: "t\u00e1c d\u1ee5ng, hi\u1ec7u \u1ee9ng",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 471,
      en: "activate",
      vn: "1. ho\u1ea1t h\u00f3a, k\u00edch ho\u1ea1t ",
      word_type: "v",
      word_type_vn: "\u0111\u1ed9ng t\u1eeb",
    },
    {
      idx: 472,
      en: "activation",
      vn: "1. ho\u1ea1t h\u00f3a (s\u1ef1), k\u00edch ho\u1ea1t (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 473,
      en: "activator",
      vn: "ho\u1ea1t h\u00f3a (ch\u1ea5t), k\u00edch ho\u1ea1t (ch\u1ea5t) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 474,
      en: "active",
      vn: "ho\u1ea1t t\u00ednh, ch\u1ee7 \u0111\u1ed9ng, t\u00edch c\u1ef1c ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 475,
      en: "activin",
      vn: "activin ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 476,
      en: "activity",
      vn: "1. ho\u1ea1t \u0111\u1ed9ng (s\u1ef1);  ho\u1ea1t l\u1ef1c;  ho\u1ea1t t\u00ednh.",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 477,
      en: "actomyosin",
      vn: "actomyosin",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 478,
      en: "acu-",
      vn: "ch\u00e2m, nh\u1ecdn, s\u1eafc b\u00e9n",
      word_type: "pref.",
      word_type_vn: "ti\u1ec1n t\u1ed1",
    },
    {
      idx: 479,
      en: "acuity",
      vn: "s\u1eafc b\u00e9n (t\u00ednh, \u0111\u1ed9), tinh t\u01b0\u1eddng (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 480,
      en: "aculeate",
      vn: "gai (c\u00f3 ), ng\u00f2i \u0111\u1ed1t (c\u00f3 )",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 481,
      en: "acuminate",
      vn: "nh\u1ecdn m\u0169i",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 482,
      en: "acupoint",
      vn: "huy\u1ec7t ch\u00e2m",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 483,
      en: "acupressure",
      vn: "ch\u00e2m \u00e9p (ph\u00e9p) (\u0111\u1ec3 c\u1ea7m m\u00e1u)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 484,
      en: "acupuncture",
      vn: "ch\u00e2m c\u1ee9u (ph\u00e9p)",
      word_type: "a,n",
      word_type_vn: "a,n",
    },
    {
      idx: 485,
      en: "acus",
      vn: "kim (c\u00e1i); m\u1ecfm h\u00ecnh kim",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 486,
      en: "acusection",
      vn: "c\u1eaft b\u1eb1ng kim \u0111i\u1ec7n (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 487,
      en: "acusector",
      vn: "dao c\u1eaft kim \u0111i\u1ec7n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 488,
      en: "acute",
      vn: "1. nh\u1ecdn  2. c\u1ea5p t\u00ednh ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 489,
      en: "acutorsion",
      vn: "xo\u1eafn b\u1eb1ng kim (ph\u00e9p) (\u0111\u1ec3 c\u1ea7m m\u00e1u)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 490,
      en: "acyanotic",
      vn: "kh\u00f4ng m\u1eafc xanh t\u00edm ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 491,
      en: "acyclic",
      vn: "1. kh\u00f4ng chu k\u1ef3  2. kh\u00f4ng v\u00f2ng (H\u00f3a)  ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 492,
      en: "acyesis",
      vn: "1. v\u00f4 sinh (n\u1eef)   2. kh\u00f4ng c\u00f3 thai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 493,
      en: "acyl",
      vn: "acyl (g\u1ed1c)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 494,
      en: "acylase",
      vn: "acylase ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 495,
      en: "acylation",
      vn: "axyl h\u00f3a",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 496,
      en: "abiogenesis",
      vn: "t\u1ef1 sinh (thuy\u1ebft)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 497,
      en: "abiosis",
      vn: "1. s\u1ed1ng ng\u1ea7m (tr\u1ea1ng th\u00e1i) . 2. m\u1ea5t sinh l\u1ef1c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 498,
      en: "abiotic",
      vn: "1. s\u1ed1ng ng\u1ea7m (tr\u1ea1ng th\u00e1i) . 2. m\u1ea5t sinh l\u1ef1c",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 499,
      en: "abiotrophy",
      vn: "m\u1ea5t s\u1ee9c s\u1ed1ng, m\u1ea5t dinh d\u01b0\u1ee1ng",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 500,
      en: "abiotrophic",
      vn: "m\u1ea5t s\u1ee9c s\u1ed1ng, m\u1ea5t dinh d\u01b0\u1ee1ng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 501,
      en: "ablepharous",
      vn: "kh\u00f4ng mi (t\u1eadt)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 502,
      en: "abulia",
      vn: "m\u1ea5t \u00fd ch\u00ed, m\u1ea5t ngh\u1ecb l\u1ef1c",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 503,
      en: "abulic",
      vn: "m\u1ea5t \u00fd ch\u00ed, m\u1ea5t ngh\u1ecb l\u1ef1c",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 504,
      en: "acantholysis",
      vn: "bong l\u1edbp gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 505,
      en: "acantholytic",
      vn: "bong l\u1edbp gai",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 506,
      en: "acanthosis",
      vn: "d\u00e0y l\u1edbp gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 507,
      en: "acanthotic",
      vn: "d\u00e0y l\u1edbp gai",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 508,
      en: "acapnia",
      vn: "gi\u1ea3m cacbon dioxyt-huy\u1ebft",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 509,
      en: "acatastasia",
      vn: "tr\u00e1i th\u00f4ng th\u01b0\u1eddng, kh\u00f4ng quy c\u1ee7",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 510,
      en: "acatastatic",
      vn: "tr\u00e1i th\u00f4ng th\u01b0\u1eddng, kh\u00f4ng quy c\u1ee7",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 511,
      en: "acathexia",
      vn: "kh\u00f4ng gi\u1eef ch\u1ea5t ti\u1ebft (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 512,
      en: "acathectic",
      vn: "kh\u00f4ng gi\u1eef ch\u1ea5t ti\u1ebft (s\u1ef1)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 513,
      en: "acheilia",
      vn: "kh\u00f4ng m\u00f4i, thi\u1ebfu m\u00f4i (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 514,
      en: "acheilous",
      vn: "kh\u00f4ng m\u00f4i, thi\u1ebfu m\u00f4i (t\u1eadt)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 515,
      en: "achlorhydria",
      vn: "thi\u1ebfu toan (axit clohydric) d\u1ecbch v\u1ecb    ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 516,
      en: "achlorhydric",
      vn: "thi\u1ebfu toan (axit clohydric) d\u1ecbch v\u1ecb    ",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 517,
      en: "achondroplastic",
      vn: "lo\u1ea1n s\u1ea3n s\u1ee5n (ch)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 518,
      en: "achromatin",
      vn: "acromatin, ch\u1ea5t kh\u00f4ng m\u00e0u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 519,
      en: "achromatinic",
      vn: "acromatin, ch\u1ea5t kh\u00f4ng m\u00e0u",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 520,
      en: "achromia",
      vn: "v\u00f4 s\u1eafc, m\u1ea5t m\u00e0u",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 521,
      en: "achromic",
      vn: "v\u00f4 s\u1eafc, m\u1ea5t m\u00e0u",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 522,
      en: "acidosis",
      vn: "nhi\u1ec5m acid",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 523,
      en: "acinesia",
      vn: "1. m\u1ea5t v\u1eadn \u0111\u1ed9ng. 2. li\u1ec7t c\u01a1 nh\u1ea5t th\u1eddi",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 524,
      en: "acinetic",
      vn: "1. m\u1ea5t v\u1eadn \u0111\u1ed9ng. 2. li\u1ec7t c\u01a1 nh\u1ea5t th\u1eddi",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 525,
      en: "acoprosis",
      vn: "ru\u1ed9t kh\u00f4ng c\u00f3 ph\u00e2n",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 526,
      en: "acoprous",
      vn: "ru\u1ed9t kh\u00f4ng c\u00f3 ph\u00e2n",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 527,
      en: "acrocephaly",
      vn: "\u0111\u1ea7u h\u00ecnh th\u00e1p  (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 528,
      en: "acrocephalous",
      vn: "\u0111\u1ea7u h\u00ecnh th\u00e1p  (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 529,
      en: "acrocinesis",
      vn: "v\u1eadn \u0111\u1ed9ng th\u00e1i qu\u00e1 (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 530,
      en: "acrocinetic",
      vn: "v\u1eadn \u0111\u1ed9ng th\u00e1i qu\u00e1 (s\u1ef1)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 531,
      en: "actinomycosis",
      vn: "b\u1ec7nh do Actinomyces. b\u1ec7nh do n\u1ea5m tia",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 532,
      en: "actinomycotic",
      vn: "b\u1ec7nh do Actinomyces. b\u1ec7nh do n\u1ea5m tia",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 533,
      en: "aberratio",
      vn: "sai, sai l\u1ec7ch (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 534,
      en: "abiuretic",
      vn: "ph\u1ea3n \u1ee9ng biuret  \u00e2m t\u00ednh",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 535,
      en: "abortient",
      vn: "g\u00e2y s\u1ea9y thai (t\u00e1c nh\u00e2n)",
      word_type: "a.n",
      word_type_vn: "a.n",
    },
    {
      idx: 536,
      en: "abrachiatism",
      vn: "thi\u1ebfu c\u00e1nh tay (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 537,
      en: "absorbency",
      vn: "1. h\u1ea5p thu (s\u1ef1) . 2. m\u1eadt \u0111\u1ed9 quang h\u1ecdc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 538,
      en: "acanthopelyx",
      vn: "khung ch\u1eadu gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 539,
      en: "acardiacus",
      vn: "kh\u00f4ng tim (qu\u00e1i thai)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 540,
      en: "acatalasemia",
      vn: "thi\u1ebfu catalase-huy\u1ebft (ch) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 541,
      en: "acaudate",
      vn: "kh\u00f4ng nh\u00e2n",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 542,
      en: "acclimatization",
      vn: "th\u00edch nghi kh\u00ed h\u1eadu (s\u1ef1), th\u00edch nghi ho\u00e0n c\u1ea3nh (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 543,
      en: "acephalism",
      vn: "kh\u00f4ng \u0111\u1ea7u (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 544,
      en: "achillotomy",
      vn: "r\u1ea1ch g\u00e2n g\u00f3t (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 545,
      en: "achordal",
      vn: "kh\u00f4ng nguy\u00ean s\u1ed1ng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 546,
      en: "achymosis",
      vn: "thi\u1ebfu d\u01b0\u1ee1ng tr\u1ea5p",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 547,
      en: "acidismus",
      vn: "nhi\u1ec5m \u0111\u1ed9c acid, nhi\u1ec5m toan (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 548,
      en: "acidophilic",
      vn: "1. \u01b0a acid. 2. \u01b0a m\u00f4i tr\u01b0\u1eddng acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 549,
      en: "aclasia",
      vn: "lo\u1ea1n s\u1ea3n c\u1ee5c b\u1ed9",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 550,
      en: "acromikria",
      vn: "nh\u1ecf c\u1ef1c (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 551,
      en: "acromyotonus",
      vn: "co c\u1ee9ng c\u01a1 \u0111\u1ea7u chi (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 552,
      en: "acroscleroderma",
      vn: "c\u1ee9ng b\u00ec c\u00e1c c\u1ef1c (bh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 553,
      en: "acyanoblepsia",
      vn: "m\u00f9 m\u00e0u lam (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 554,
      en: "acyanopsia",
      vn: "m\u00f9 m\u00e0u lam (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 555,
      en: "abiogenous",
      vn: "t\u1ef1 sinh (thuy\u1ebft)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 556,
      en: "ablepharon",
      vn: "kh\u00f4ng mi (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 557,
      en: "acapnic",
      vn: "gi\u1ea3m cacbon dioxyt-huy\u1ebft",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 558,
      en: "achondroplasty",
      vn: "lo\u1ea1n s\u1ea3n s\u1ee5n (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 559,
      en: "acidotic",
      vn: "nhi\u1ec5m acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 560,
      en: "aberration",
      vn: "sai, sai l\u1ec7ch (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 561,
      en: "abiuret",
      vn: "ph\u1ea3n \u1ee9ng biuret  \u00e2m t\u00ednh",
      word_type: "a.n",
      word_type_vn: "a.n",
    },
    {
      idx: 562,
      en: "abortifacient",
      vn: "g\u00e2y s\u1ea9y thai (t\u00e1c nh\u00e2n)",
      word_type: "a.n",
      word_type_vn: "a.n",
    },
    {
      idx: 563,
      en: "abrachia",
      vn: "thi\u1ebfu c\u00e1nh tay (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 564,
      en: "absorbance",
      vn: "1. h\u1ea5p thu (s\u1ef1) . 2. m\u1eadt \u0111\u1ed9 quang h\u1ecdc",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 565,
      en: "acanthopelvis ",
      vn: "khung ch\u1eadu gai",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 566,
      en: "acardius",
      vn: "kh\u00f4ng tim (qu\u00e1i thai)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 567,
      en: "acatalasia",
      vn: "thi\u1ebfu catalase-huy\u1ebft (ch) ",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 568,
      en: "acaudal",
      vn: "kh\u00f4ng nh\u00e2n",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 569,
      en: "acclimation",
      vn: "th\u00edch nghi kh\u00ed h\u1eadu (s\u1ef1), th\u00edch nghi ho\u00e0n c\u1ea3nh (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 570,
      en: "acclimatation",
      vn: "th\u00edch nghi kh\u00ed h\u1eadu (s\u1ef1), th\u00edch nghi ho\u00e0n c\u1ea3nh (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 571,
      en: "acephalia",
      vn: "kh\u00f4ng \u0111\u1ea7u (qu\u00e1i t\u01b0\u1ee3ng)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 572,
      en: "achillotenotomy",
      vn: "r\u1ea1ch g\u00e2n g\u00f3t (thth)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 573,
      en: "achordate",
      vn: "kh\u00f4ng nguy\u00ean s\u1ed1ng",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 574,
      en: "achymia",
      vn: "thi\u1ebfu d\u01b0\u1ee1ng tr\u1ea5p",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 575,
      en: "acidism",
      vn: "nhi\u1ec5m \u0111\u1ed9c acid, nhi\u1ec5m toan (s\u1ef1)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 576,
      en: "acidophil",
      vn: "1. \u01b0a acid. 2. \u01b0a m\u00f4i tr\u01b0\u1eddng acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 577,
      en: "acidophile",
      vn: "1. \u01b0a acid. 2. \u01b0a m\u00f4i tr\u01b0\u1eddng acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 578,
      en: "aclasis",
      vn: "lo\u1ea1n s\u1ea3n c\u1ee5c b\u1ed9",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 579,
      en: "acromicria",
      vn: "nh\u1ecf c\u1ef1c (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 580,
      en: "acromyotonia",
      vn: "co c\u1ee9ng c\u01a1 \u0111\u1ea7u chi (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 581,
      en: "acrosclerosis",
      vn: "c\u1ee9ng b\u00ec c\u00e1c c\u1ef1c (bh)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 582,
      en: "abiogenetic",
      vn: "t\u1ef1 sinh (thuy\u1ebft)",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 583,
      en: "ablepharia",
      vn: "kh\u00f4ng mi (t\u1eadt)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 584,
      en: "acapnial",
      vn: "gi\u1ea3m cacbon dioxyt-huy\u1ebft",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
    {
      idx: 585,
      en: "achondroplasia",
      vn: "lo\u1ea1n s\u1ea3n s\u1ee5n (ch)",
      word_type: "n",
      word_type_vn: "danh t\u1eeb",
    },
    {
      idx: 586,
      en: "acidosic",
      vn: "nhi\u1ec5m acid",
      word_type: "a",
      word_type_vn: "t\u00ednh t\u1eeb",
    },
  ];
  const items2 = [
    {
        "idx": 1,
        "eng": "ab-",
        "vn": " r\u1eddi, xa, gi\u1ea1ng,t\u00e1ch xa",
        "word_type": "pref.",
        "word_type_vn": "ti\u1ec1n t\u1ed1"
    },
    {
        "idx": 2,
        "eng": "abacterial",
        "vn": "kh\u00f4ng c\u00f3 vi khu\u1ea9n, phi khu\u1ea9n",
        "word_type": "a",
        "word_type_vn": "t\u00ednh t\u1eeb"
    },
    {
        "idx": 3,
        "eng": "abaptiston",
        "vn": "khoan s\u1ecd an to\u00e0n ",
        "word_type": "n",
        "word_type_vn": "danh t\u1eeb"
    },
    {
        "idx": 4,
        "eng": "abaragnosis",
        "vn": "m\u1ea5t nh\u1eadn th\u1ee9c tr\u1ecdng l\u01b0\u1ee3ng, m\u1ea5t tr\u1ecdng l\u01b0\u1ee3ng th\u1ee9c ",
        "word_type": "n",
        "word_type_vn": "danh t\u1eeb"
    },
    {
        "idx": 5,
        "eng": "abarthrosis",
        "vn": "kh\u1edbp \u0111\u1ed9ng ",
        "word_type": "n",
        "word_type_vn": "danh t\u1eeb"
    },
    {
        "idx": 6,
        "eng": "abarticular",
        "vn": "1. kh\u00f4ng g\u00e2y t\u1ed5n kh\u1edbp. 2.ngo\u00e0i kh\u1edbp ",
        "word_type": "a",
        "word_type_vn": "t\u00ednh t\u1eeb"
    },
    {
        "idx": 7,
        "eng": "abarticulation",
        "vn": "1. sai kh\u1edbp. 2. kh\u1edbp \u0111\u1ed9ng",
        "word_type": "n",
        "word_type_vn": "danh t\u1eeb"
    }
]


  const handleOnSearch = (string) => {
    axios
    .get("http://127.0.0.1:5000/search_bar/", {
      params: {word:string},
    })
    .then((response) => {
      // console.log(response.data)
      props.setItems(response.data)
    })
  };

  // const itemsReturn = () =

  const handleOnHover = (result) => {
    // console.log(result);
  };

  const handleOnSelect = (item) => {
    axios
      .get("http://127.0.0.1:5000/audio/", {
        params: { en_word:item.en, vi_word:item.vn},
      })
      .then((response) => {
        
      })

      props.setShowResult(!props.showResult);
      props.setResult({
        en: `${item.en}`,
        vn: `${item.vn}`,
        type: `${item.word_type}`,
        type_vn: `${item.word_type_vn}`,
      });
  };

  

  const handleOnFocus = () => {
    // console.log("Focused");
  };

  const handleOnClear = () => {
    // console.log("Cleared");
  };

  const formatResult = (item) => {
    return (
      <>
        <span style={{ display: "block", textAlign: "left" }}>
          {fromEng ? item.en : item.vn} ({item.word_type})
        </span>
      </>
    );
  };

  return (
    <div className="header__search">
      <div style={{ width: 400 }}>
        <ReactSearchAutocomplete
          items={props.items}
          onSearch={handleOnSearch}
          onHover={handleOnHover}
          onSelect={handleOnSelect}
          onFocus={handleOnFocus}
          autoFocus
          onClear={handleOnClear}
          formatResult={formatResult}
          fuseOptions={{ keys: fromEng ? ["en"] : ["vn"] }}
          resultStringKeyName={fromEng ? ["en"] : ["vn"]}
        />
      </div>
    </div>
  );
}

export default Search;
